version: '3.2'
services:
  mysql:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
    networks:
      - vault-net
  vault:
    image: "vault"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - vault-net
networks:
  vault-net: