version: '3.2'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_CLOUD_VAULT_TOKEN=${VAULT_APP_TOKEN}
      - SPRING_CLOUD_VAULT_HOST=vault
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306
    networks:
      - vault-net
networks:
  vault-net: